baseURL = "https://gear.codes"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "Gears"
disableKinds = ["RSS"]
googleAnalyticsID = "G-ZVMJB2YJS2"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  googleAnalyticsID = "G-ZVMJB2YJS2"

  # Subtitle for home
  homeSubtitle = "Software development tools"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "We focus on creating effective tools for software development"
  keywords = "software, development, tools"
  images = [""]

[taxonomies]
  tag = "tags"
  category = "categories"

[languages]
  [languages.en]
    title = "Gears"
    subtitle = "Software development"
    keywords = "software, development, tools, iOS, mobile"
    #copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    #readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "ceres"
    name       = "Ceres: iOS Simulator Gear"
    url        = "/ceres"
